// Products state
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

// Orders state
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const CONFIRM_ORDER_MEAL = 'CONFIRM_ORDER_MEAL';
export const SHOW_SUMMARY = 'SHOW_SUMMARY';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
